WebGroup/matcher/matcher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('matchingsite.urls')),
    path('admin/', admin.site.urls),
]

#URL to retrieve where the profile images will go to
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebGroup/matcher/matchingsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    PasswordResetView,PasswordResetDoneView, PasswordResetConfirmView,PasswordResetCompleteView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    #mainpage url
    path('', views.home, name='home'),
    #logout url
    path('logout/', views.logout, name='logout'),
    #login url
    path('login/', views.login, name='login'),
    #register url
    path('register/', views.register, name='register'),
    #change password url
    path('change-password/', views.change_password, name='change_password'),
    #edit profile url
    path('editprofile/', views.edit_profile, name = 'edit_profile'),
    #view profile url
    path('viewprofile/', views.view_profile, name='view_profile'),
    #view other members profile url
    path('viewprofilepk/<int:pk>', views.viewprofilepk, name='viewprofile'),
    #this url is to check the user profile when the ajax calls are made.
    path('listmembers/viewprofilepk/<int:pk>', views.viewprof, name='viewprofile'),
    #list of members url
    path('listmembers/', views.list_members, name='members'),
    #url for gender ajax feature
    path('gender/', views.getgender, name='gender'),
    #url for age range ajax feature
    path('agerange/', views.age_range, name='agerange'),
    #url for age and gender ajax feature
    path('ageandg/', views.ageAndGender, name='ageandg'),
    #url for search by first name ajax feature
    path('search/', views.searchuser, name='search'),
    #url for google maps location feature and doodle
    path('locate/', views.locate, name='locate'),
    #url for the ajax call to upload image
    path('uploadimage/', views.upload_image, name='uploadimage'),

    #PASSWORD RESET URLS
    path('password_reset/', PasswordResetView.as_view(template_name='registration/password_reset_form.html',success_url='done/'), name="password_reset"),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),    

    
]

WebGroup/matcher/matchingsite/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

#MODEL FOR USERPROFILE
class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F' , 'Female'),
        )
    user = models.ForeignKey(
        to=User,
        null=True,
        on_delete=models.CASCADE
    )
    profile_pic = models.ImageField(upload_to='images/')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    gender = models.CharField(max_length=100, choices= GENDER_CHOICES)
    dob = models.DateField(null=True)
    location = models.CharField(max_length=100,null=True)
    allow_location = models.BooleanField(default=True)

    def __str__(self):
        return str(self.user)
    @property
    def has_member(self):
        return hasattr(self, 'member') and self.member is not None

    @property
    def member_check(self):
        return str(self.member) if self.has_member else 'NONE'

#MODEL FOR HOBBIES
class Hobbies(models.Model):
    list_Of_Hob = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.list_Of_Hob)
    
#MODEL FOR MEMBER
class Member(User):
    #One user has one user profile.
    user = models.OneToOneField(
        to=UserProfile,
        blank=True,
        null=True,
        on_delete=models.CASCADE
        )
    #many2many field between user and hobbies.
    hobbies = models.ManyToManyField(
        Hobbies,
        blank=True,
        symmetrical=False,
    )


    def __str__(self):
        return self.username
    @property
    def hobby_count(self):
        return self.hobbies.count()

    @property
    def hobbies_count(self):
        return Member.objects.filter(hobbies__id=self.id)

WebGroup/matcher/matchingsite/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import UserProfile, Member, Hobbies
from django.contrib.auth.forms import UserCreationForm

#Added a TextInput class to add a placeholder to the location field
class TextInput(forms.TextInput):
    input_type = 'text'

#Registration form class to display fields from Djangos User model.
class RegistrationForm(UserCreationForm):
    class Meta:
        model = Member
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

#Method which allows to override the 'required' attribute of the field.
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

#UserProfile form class to display fields fromUserprofile Model.      
class UserProfileForm(ModelForm):

    class Meta:
        model= UserProfile
        fields= ['profile_pic', 'first_name', 'last_name', 'email', 'gender', 'dob', 'location', 'allow_location']
        labels = {
        "profile_pic": "Profile Image",
        "first_name" : "First Name",
        "last_name" : "Surname",
        "dob" : "Date Of Birth",      
    }
        #widget which inputs a placeholder in location field.
        widgets = {
            'location': TextInput(attrs={'placeholder': 'Please enter accurate location for best results.'}),
        }

    #Method which allows to override the 'required' attribute of the field.
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        self.fields['profile_pic'].required = False
        self.fields['first_name'].required = False
        self.fields['last_name'].required = False
        self.fields['email'].required = False
        self.fields['dob'].widget.attrs['readonly'] = True
        

#Edit hobbies form class to display fields from Custom Member model. 
class EditHobbies(ModelForm):

    class Meta:
        model = Member
        fields=['hobbies']

    
    

WebGroup/matcher/matchingsite/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from .forms import RegistrationForm, UserProfileForm, EditHobbies
from django.contrib.auth.models import User
from .models import UserProfile, Hobbies, Member
from django.contrib.auth.password_validation import CommonPasswordValidator
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
#importing the login form and password change form from djangos auth forms.
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
import datetime as D
import sys
import json
from datetime import date
from django.utils.timezone import now
#library to use for counting hobbies.
from django.db.models import Count
from django.contrib.auth import update_session_auth_hash,  authenticate,login as loginuser
#library for the paginator
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.exceptions import ValidationError
from django.forms import forms
from django.db.models import Q


# Create your views here.
#This view is to check whether the logged in user is in the session and is used as a decorator to store the logged in users details.
def loggedin(view):
    def mod_view(request):
        if 'username' in request.session:
            username = request.session['username']
            try: user = Member.objects.get(username=username)
            except Member.DoesNotExist: raise Http404('Member does not exist')
            return view(request, user)
        else:
            return render(request,'matchingsite/logout.html',{})
    return mod_view

#view for home index page
def home(request):
    if 'username' in request.session:
        return redirect('view_profile')

    else:
        return render(request, 'base.html')

#view function to register the user
def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        #form which holds the data posted by the user
        form = RegistrationForm(request.POST)
        #each value is stored in a variable
        username = request.POST['username']
        first_name =request.POST['first_name']
        surname = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password1']
        #this checks whether the email already exists.
        if Member.objects.filter(email=email).exists():
            messages.success(request, 'Email already in use. Please try again with a different email.')
            return redirect('register')
        if form.is_valid():
            #checks whether the user is new or if they already exists.
            user, created = Member.objects.get_or_create(username=username, email=email, first_name=first_name, last_name=surname, password = password)
            if created:
                user.set_password(password)
                user.save()
                profile = UserProfile()
                profile.user=user
                profile.save()
                user.user=profile
                user.save()
            messages.success(request,'Account has been created successfully.')
            return redirect('login')
        
        else:
            messages.success(request, 'Please make sure you are entering the correct values')
           
    else:
        form = RegistrationForm()
    return render(request, 'matchingsite/register.html', {'form': form})

#view function to allow the user to login.
def login(request):
    #checks to see whether the user is already logged in. If yes, redirect them to their profile
    if 'username' in request.session:
        return redirect('view_profile')
    
    if request.method=='POST':
        #stores the request,post information in the form.
        form = AuthenticationForm(request.POST)
        #gets the user name and password for the login page
        username = request.POST['username']
        password = request.POST['password']
        #authenticate() method to verify the credentials
        user = authenticate(username=username, password=password)
        if user is not None:
            user = Member.objects.get(username=username)
            # remember user in session variable
            request.session['username'] = username
            request.session['password'] = password
            context = {
               'user': user,
               'loggedin': True,
            }
            response = render(request, 'matchingsite/viewprofile.html', context)
            # remember last login in cookie
            now = D.datetime.utcnow()
            max_age = 365 * 24 * 60 * 60  #one year
            delta = now + D.timedelta(seconds=max_age)
            format = "%a, %d-%b-%Y %H:%M:%S GMT"
            expires = D.datetime.strftime(delta, format)
            response.set_cookie('last_login',now,expires=expires)
            return response
        else:
            messages.error(request,'Username or password is incorrect.')
            return redirect('login')
             
    else:
        form = AuthenticationForm()
        return render(request,'matchingsite/login.html', {'form':form,})

@loggedin
def change_password(request, user):
    #This view was used from djangos change password forms and uses update_session_auth_hash to update the password.
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, "Password has been changed")
            return redirect('view_profile')
        else:
            messages.error(request, "Old password maybe incorrect or two passwords do not match. Please try again.")
            form = PasswordChangeForm(user=user)
            context = {'form': form, 'loggedin':True, 'user':user}
            return render(request, 'matchingsite/change_password.html', context)
            
    else:
        form = PasswordChangeForm(user=user)
        context = {'form': form, 'loggedin':True, 'user':user}
        return render(request, 'matchingsite/change_password.html', context)

#view function to logout. Redirects to base page.
@loggedin
def logout(request, user):
    request.session.flush()
    return redirect('home')

#view function which allows the user to display another users profile
def viewprofilepk(request, pk):
    try: user = Member.objects.get(id=pk)
    except Member.DoesNotExist: raise Http404('Member does not exist')
    context = {
        'user': user,
        'loggedin': True
    }
    return render(request, 'matchingsite/viewprofilepk.html', context)

#this view is used for the ajax function for displaying a quick view of the users profile in the table.
def viewprof(request, pk):
    try: user = Member.objects.get(id=pk)
    except Member.DoesNotExist: raise Http404('Member does not exist')
    data = {
            'user':str(user),
            'pic':json.dumps(str(user.user.profile_pic)),
            'email':user.email,
            'gender':user.user.gender,
            'dob':user.user.dob,
            }
    return JsonResponse(data)

#view function for the user to display their own profile.
@loggedin
def view_profile(request, user):
    try: user = Member.objects.get(user=user.user)
    except Member.DoesNotExist: raise Http404('Member does not exist')
    context = {
        'user': user,
        'loggedin': True
    }
    return render(request, 'matchingsite/viewprofile.html', context)

#view function to allow the user to edit their profile.
@loggedin
def edit_profile(request, user):
    if request.method == 'POST':
        #as it is two different forms, retrieve the values from both.
        form = UserProfileForm(request.POST, request.FILES, instance=user.user)
        formHob = EditHobbies(request.POST, instance=user)
        #checks to see if user has a picture.
        if 'profile_pic' in request.FILES:
            ppic = request.FILES['profile_pic']
        fname = request.POST['first_name']
        lname = request.POST['last_name']
        email = request.POST['email']
        gender = request.POST['gender']
        dob = request.POST['dob']
        loc = request.POST['location']
        if 'hobbies' in request.POST:
            hobs = request.POST['hobbies']
        #django displays output for checkbox as on so condition was used to set it to true or false as Djangos db allows only True/False.
        allowloc = request.POST.get('allow_location')
        if allowloc =='on':
            check = True
        else:
            check = False

        #This is a condition to check if the user already has a profile then update the existing information.
        if user.user:
            if 'profile_pic' in request.FILES:
                user.user.profile_pic =ppic
            user.user.first_name = fname
            user.user.last_name =lname
            user.user.email = email
            user.user.gender = gender
            user.user.dob = dob
            user.user.allow_location = check
            user.user.location = loc
            user.user.save()
            user.save()
            hobbies = formHob.save(commit=False)
            hobbies.save()
            #save the hobbies using m2m() as it is many2many field
            formHob.save_m2m()

        #if the user does not have values in their profile then store the new values.
        else:
            profile = UserProfile(profile_pic=ppic, first_name=fname, last_name=lname, email=email, gender=gender, dob=dob, location=loc)
            profile.save()
            user.user=profile
            user.save()
            hobbies = formHob.save(commit=False)
            hobbies.save()
            #save the hobbies using m2m() as it is many2many field
            formHob.save_m2m()
            
        return redirect('view_profile')

    else:

WebGroup/matcher/matchingsite/templates/matchingsite/ageandg.html
    <!-- If there are users that match the query, append this html to the table. -->
    {% if ageandg.count > 0 %}
      <thead>
                              <tr>
                                <th> Rank </th>
                                <th> Image</th>
                                <th> Name</th>
                                <th> Email</th>
                                <th> Gender</th>
                                <th> DOB</th>
                                <th> Hobbies </th>
                              </tr>
                             </thead>
             {% for both in ageandg %}
             <tbody id="{{both.id}}">
                            <tr class ="members">
                               <td class="nr">
                              </td>
                                {% if both.user.profile_pic %}
                                <td width="10">
                                    <img class="pull-left img-circle nav-user-photo" width="50" src="{{ both.user.profile_pic.url }}" />  
                                </td>
                                </td>
                                {% else %}
  <td width="10"><img class="pull-left img-circle nav-user-photo" width="50" src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png">
  </td> 
                                {% endif %}
                                <td>
                                    <a href="/viewprofilepk/{{both.id}}"><p>{{ both.first_name}}</p></a><br><i class="fa fa-envelope"></i>
                                </td>
                                <td>
                                  {{both.email}}
                                </td>

                                <td>
                                  {{both.user.gender}}
                                </td>

                                <td>
                                  {{both.user.dob}}
                                </td>
                                <td>
                                  {% for hobby in both.hobbies.all %}
                                    <p>{{hobby}}</p>
                                  {% endfor %}
                                </td>
                            </tr>
                        </tbody>
                            {% endfor %}
                            {% else %}

  <li>No results.</li>

  {% endif %}  
  <!-- Putting a rank on the table based on how many rows.-->
     <script>

    var a = document.getElementsByClassName("nr");
    for (var i = 0; i < a.length; i++) {
        a[i].innerHTML = (i+1)+".";
    }
  

</script>

WebGroup/matcher/matchingsite/templates/matchingsite/agemembers.html
 <!-- If there are users that match the query, append this html to the table. -->
    {% if ages.count > 0 %}
       <thead>
                              <tr>
                                <th> Rank </th>
                                <th> Image</th>
                                <th> Name</th>
                                <th> Email</th>
                                <th> Gender</th>
                                <th> DOB</th>
                                <th> Hobbies </th>
                              </tr>
                             </thead>
             {% for age in ages %}
             <tbody id="{{age.id}}">
                            <tr class ="members">
                              <td class="nr">
                              </td>
                                {% if age.user.profile_pic %}
                                <td width="10">
                                    <img class="pull-left img-circle nav-user-photo" width="50" src="{{ age.user.profile_pic.url }}" />  
                                </td>
                                {% else %}
  <td width="10"><img class="pull-left img-circle nav-user-photo" width="50" src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png">
  </td>      
                                {% endif %}
                                <td>
                                    <a href="/viewprofilepk/{{age.id}}"><p>{{ age.first_name}}</p></a><br><i class="fa fa-envelope"></i>
                                </td>
                                <td>
                                  {{age.email}}
                                </td>

                                <td>
                                  {{age.user.gender}}
                                </td>

                                <td>
                                  {{age.user.dob}}
                                </td>
                                 <td>
                                  {% for hobby in age.hobbies.all %}
                                    <p>{{hobby}}</p>
                                  {% endfor %}
                                </td>
                            </tr>
                        </tbody>
                            {% endfor %}
                         {% else %}
  <li>No results.</li>

  {% endif %}
  <!-- Putting a rank on the table based on how many rows.-->
          <script>

    var a = document.getElementsByClassName("nr");
    for (var i = 0; i < a.length; i++) {
        a[i].innerHTML = (i+1)+".";
    }
  

</script>  

WebGroup/matcher/matchingsite/templates/matchingsite/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head %}
<title>Change Password</title>
{% endblock %}
{% block content %}
<!-- Page to allow users to change their password whilst loggedin. -->
<div class="signup-form">
    <form method="post">
    <h2>{{user}}</h2>
     {% csrf_token %}
    <p class="hint-text">Change your password here.</p>
        <div class="form-group">
         <div class="row">
        {{form | crispy}}
      
         <div class="form-group loginbut" style="width:100%">
            <button type="submit" class="btn btn-primary btn-block outline">Update</button>
      </div>
         </div>
        </div>
      {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
 {% for message in messages %}

                    <div class="alert alert-danger">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
            {% endfor %}
    </form>
</div>  
{% endblock content %}                   

WebGroup/matcher/matchingsite/templates/matchingsite/gendermembers.html
   <!-- If there are users that match the query, append this html to the table. -->
    {% if genders.count > 0 %}
    <thead>
                              <tr>
                                <th> Rank</th>
                                <th> Image</th>
                                <th> Name</th>
                                <th> Email</th>
                                <th> Gender</th>
                                <th> DOB</th>
                                <th> Hobbies </th>
                              </tr>
                             </thead>
             {% for gender in genders %}
            <tbody id="{{gender.id}}">
                            <tr class ="members">
                              <td class="nr">
                              </td>
                                {% if gender.user.profile_pic %}
                                <td width="10">
                                    <img class="pull-left img-circle nav-user-photo" width="50" src="{{ gender.user.profile_pic.url }}" />  
                                </td>
                                {% else %}
  <td width="10"><img class="pull-left img-circle nav-user-photo" width="50" src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png">
  </td>   
                                {% endif %}
                                <td>
                                    <a href="/viewprofilepk/{{gender.id}}"><p>{{ gender.first_name}}</p></a><br><i class="fa fa-envelope"></i>
                                </td>
                                <td>
                                  {{gender.email}}
                                </td>

                                <td>
                                  {{gender.user.gender}}
                                </td>

                                <td>
                                  {{gender.user.dob}}
                                </td>
                                <td>
                                  {% for hobby in gender.hobbies.all %}
                                    <p>{{hobby}}</p>
                                  {% endfor %}
                                </td>
                            </tr>
                        </tbody>
                            {% endfor %}
                            {% else %}

  <li>No results.</li>

  {% endif %}  
<!-- Putting a rank on the table based on how many rows.-->
          <script>

    var a = document.getElementsByClassName("nr");
    for (var i = 0; i < a.length; i++) {
        a[i].innerHTML = (i+1)+".";
    }
  

</script>                    
    
                        

WebGroup/matcher/matchingsite/templates/matchingsite/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<!-- Login form to display to the user. Uses djangos LoginForm -->
<script>
$(document).ready(function(){    
    $("#main").hide();
});
</script> 
<div class="container editP">
<div class="signup-form">
   {% if loggedin %}
           You are now logged in.
       {% else %}
    <form method="post">
    <h2>Sign in</h2>
     {% csrf_token %}
    <p class="hint-text">Log in with your username and password.</p>
    <div class="form-group">
        <div class="row">
        {{form | crispy}}
      
        <div class="form-group" style="width:100%">
        <small class="text-muted">
                <a class="ml-2" href="{% url 'password_reset' %}">Forgot Password?</a>
        </small> &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
        <small class="text-muted">Don't have an account?
                <a class="ml-2" href="{% url 'register' %}">Register here.</a>
        </small> 
              
        </div>
        <div class="form-group loginbut" style="width:100%">
        <button type="submit" class="btn btn-primary btn-block outline">Login</button>
        </div>
        </div>
    </div>

      
    </form>

    {% for message in messages %}

                    <div class="alert alert-info">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
            {% endfor %}
        {% endif %}
</div>  
</div>
{% endblock %}                  

WebGroup/matcher/matchingsite/templates/matchingsite/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock content%}

WebGroup/matcher/matchingsite/templates/matchingsite/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<script>
  //This was implemented for Browser compability. Safari sees the date picker as a text type so a check is made to see if the input type is not date.
  $(document).ready(function(){
    if ( $('[type="date"]').prop('type') != 'date' ) {
    $('[type="date"]').datepicker(
      {
        dateFormat: 'yy-mm-dd',
        maxDate:'2000-12-31',
        changeYear: true,
        changeMonth:true,
        yearRange:'c-100:c+10',
      });
}

  });


  $(document).ready(function(){

      $('#id_dob').datepicker(
      {
        dateFormat: 'yy-mm-dd',
        maxDate:'2000-12-31',
        changeYear: true,
        changeMonth:true,
        yearRange:'c-100:c+10',
      });
  })

//Runs ajax function on clicking image.
  $(document).ready(function(){
     $('#profile-img').click(function() {
       $("#img_file").click();
   });
  });

//Initally the profile image change was showing as Currently and Change: This did not look good so hiding that div is appropriate.
  $(document).ready(function(){    
    $("#div_id_profile_pic").hide();
});
</script>

<!-- Div to display the custom edit profile form. -->
<div class="container editP">
 <div class="row">
    <div class="col-sm-6" > 
<div class="signup-form pPicC">
    <form method="post" enctype="multipart/form-data">
       <input type="file" id="img_file" style="display:none;">
    <h2 class="uName"> {{user}}</h2>
     {% csrf_token %}
    <p class="hint-text">Make changes to your profile.</p>
      
        {% if user.user.profile_pic %}   
        <div class="form-group pPic"> 
   <a class="profP" ><img id='profile-img' src="{{ user.user.profile_pic.url }}" width="240"></a> 
  </div>
  {% else %}
  <img id='profile-img' src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png" width="240" class="rounded-circle">
    {% endif %}
    <p class="hint-text">Click profile image to change.</p>
    <progress id="progressBar" value="0" max="100" style="width:150px;display:none;">
      </progress>
  </div>
</div>
    <div class="col-sm-6">   
<div class="form-group formP">
        <div class="row">
        {{form | crispy}}
        {{ form.location.help_text |safe}}
        {{ formHob | crispy}}
        <div class="form-group loginbut" style="width:100%">
            <button type="submit" class="btn btn-primary btn-block outline ">Make changes</button>
        </div>
    </form>
</div> 
</div>
</div> 
</div>
</div>
{% endblock content %}                   

WebGroup/matcher/matchingsite/templates/matchingsite/test.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container editP">
 <div class="row">
    <div class="col-sm-6" > 
<div class="signup-form pPicC">
    <form method="post" enctype="multipart/form-data">
    <h2 class="uName"> {{user}}</h2>
     {% csrf_token %}
    <p class="hint-text">Make changes to your profile.</p>
      
        {% if user.user.profile_pic %}   
        <div class="form-group pPic"> 
   <a class="profP" ><img src="{{ user.user.profile_pic.url }}" width="240"></a> 
  </div>
  {% else %}
  <img src="https://www.jamf.com/jamf-nation/img/default-avatars/generic-user-purple.png" class="rounded-circle">
    {% endif %}
    
  </div>
</div>
    <div class="col-sm-6">   
<div class="form-group formP">
        <div class="row">
        {{form | crispy}}
        {{ formHob | crispy}}
        </div>          
      </div>
    <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block outline ">Make changes</button>
        </div>
    </form>
</div> 
</div> 
</div>
</div>
{% endblock content %}                   